services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: hasloRoot
      MYSQL_DATABASE: projektdb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - ci-net

  node-app:
    image: node-app:latest      # zamiast build: context
    container_name: node-app
    restart: always              # automatyczne wznawianie
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: hasloRoot
      MYSQL_DATABASE: projektdb
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - ci-net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-net
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - node-app
      - jenkins
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ci-net
    ports:
      - "80:80"

volumes:
  mysql_data:
  jenkins_home:

networks:
  ci-net:
    driver: bridge

